services:

  redis:
    image: library/redis:5.0-alpine
    restart: unless-stopped
    networks:
      - net01
    volumes:
      - redis_data:/data

  db:
    env_file: .env
    image: postgres:16
    restart: unless-stopped
    networks:
      - net01
    volumes:
      - db_home:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=v18_odoo

  odoo:
    env_file: .env
    user: "root"

    build:
      context: ./18.0
      dockerfile: Dockerfile

    image: erpgap
    restart: unless-stopped
    command: ["/startup.sh"]

    ports:
      - "8069:8069"

    volumes:
      - odoo_home:/var/lib/odoo
      - odoo_extra:/mnt/extra-addons
      - ./18.0/odoo.conf:/etc/odoo/odoo.conf

    depends_on:
      - db

    networks:
      - net01

  alokai:
    env_file: .env

    image: alokai-sfui2

    restart: unless-stopped

    ports:
      - "3000:3000"

    volumes:
      - nuxt_build:/apt/.nuxt

    depends_on:
      - odoo
      - redis

    networks:
      - net01

volumes:
  db_home:
  odoo_home:
  odoo_extra:
  redis_data:
  nuxt_build:

networks:
  net01:
